#!/usr/bin/env bash
#
# power-profiles-daemon implementation:
# needs package power-profiles-daemon installed and the service running see here:
# https://wiki.archlinux.org/title/CPU_frequency_scaling#power-profiles-daemon
# used in i3-blocks: ~/.config/i3/i3blocks.conf together with: ~/.config/i3/scripts/power-profiles

# script to show current power profile

status=$(powerprofilesctl get)

icon=""
color="#717171"

if [ "$status" = "performance" ]; then
    icon="󰓅"
    color="#ffff00"
elif [ "$status" = "balanced" ]; then
    icon=""
    color="#717171"
elif [ "$status" = "power-saver" ]; then
    icon=""
    color="#407437"
fi

# long text
echo $icon
# short text
echo $icon
# color
echo $color
